types_action:
  - track:  "Nome da Musica"
  - artist: "Nome do Artista"
  - album:  "Nome do Album"
  - genre:  "Gênero Musical"

lamp:
  mode: "LCT001"
  endpoint: "http://192.168.1.100/api/edersondelima/"
